apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: echo-api
  description: echo api
  links:
    - url: http://echoapi.cloudapp.net/api
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: production
  owner: demo-team
  system: demo-app
  consumesApi: 
    - calc-api
  definition:
    $text: https://github.com/vieiraae/servicecatalog/blob/main/echo-api/openapi.json
