
on: [push]

name: ExportAllAPIsFromAPIM
permissions:
      id-token: write
      contents: read
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 
    - run: mkdir -p dir1
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: dir1 
    
    - name: 'Get RG with powershell action'
      uses: azure/powershell@v1
      with:
       inlineScript: |
         $context = New-AzApiManagementContext -ResourceGroupName "alexviei-integration" -ServiceName "azure-apim-lab"
         $apis = Get-AzApiManagementApi -Context $context
         foreach($api in $apis) {
           if ($api.ApiType = 'http') {
             Export-AzApiManagementApi -Context $context -ApiId $api.ApiId -SpecificationFormat OpenApiJson -SaveAs "$api.ApiId" 
           }
         }         
       azPSVersion: "latest"
