
on: [push]

name: ExportAllAPIsFromAPIM
permissions:
      id-token: write
      contents: read
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 
    
    - name: 'Get RG with powershell action'
      uses: azure/powershell@v1
      with:
       inlineScript: |
         $context = New-AzApiManagementContext -ResourceGroupName "alexviei-integration" -ServiceName "azure-apim-lab"
         $apis = Get-AzApiManagementApi -Context $context
         foreach($api in $apis){
             if ($api.ApiType = 'http') {
                 if (Test-Path -Path $api.ApiId) {
                     $dir = Get-Item $api.ApiId
                 } else {
                     $dir = New-Item $api.ApiId -Type Directory
                 }
                 $filename = "$($dir.FullName)/openapi.json"
                 if (Test-Path $fileName) {
                    Remove-Item $fileName
                 }
                 Export-AzApiManagementApi -Context $context -ApiId $api.ApiId -SpecificationFormat OpenApiJson -SaveAs $filename
             }
         }
         git add .
         git commit -m "Importing APIs from Azure APIM"
         git push
       azPSVersion: "latest"
