
on: [push]

name: ExportAllAPIsFromAPIM
permissions:
      id-token: write
      contents: read
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: show az version
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version
          
    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 
    - name: 'Get RG with powershell action'
      uses: azure/powershell@v1
      with:
       inlineScript: |
         $context = New-AzApiManagementContext -ResourceGroupName "alexviei-integration" -ServiceName "azure-apim-lab"
         Get-AzApiManagementApi -Context $context
       azPSVersion: "latest"
