
on: [push]

name: ExportAllAPIsFromAPIM
permissions:
      id-token: write
      contents: write
      pull-requests: write
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 
    - name: Checkout files
      uses: actions/checkout@v2
    - name: 'Export Azure API Management APIs'
      uses: azure/powershell@v1
      with:
       inlineScript: |
         $context = New-AzApiManagementContext -ResourceGroupName "alexviei-integration" -ServiceName "azure-apim-lab"
         $apis = Get-AzApiManagementApi -Context $context
         foreach($api in $apis){
             if ($api.ApiType = 'http') {
                 if (Test-Path -Path $api.ApiId) {
                     $dir = Get-Item $api.ApiId
                 } else {
                     $dir = New-Item $api.ApiId -Type Directory
                 }
                 $filename = "$($dir.FullName)/openapi.json"
                 if (Test-Path $fileName) {
                    Remove-Item $fileName
                 }
                 Set-Content -Path "$($dir.FullName)/catalog-info.yaml" -Value "apiVersion: backstage.io/v1alpha1`nkind: API`nmetadata:`n  name: calc-api`n  description: $($api.Description)`n  links:`n    - url: $($api.ServiceUrl)`n      title: API Definition`n      icon: docs`nspec:`n  type: openapi`n  lifecycle: experimental`n  owner: demo-team`n  system: demo-app`n  definition:`n    `$text: https://github.com/vieiraae/servicecatalog/blob/main/$($api.ApiId)/openapi.json"                 
                 Export-AzApiManagementApi -Context $context -ApiId $api.ApiId -SpecificationFormat OpenApiJson -SaveAs $filename
             }
         }
       azPSVersion: "latest"
    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git diff-index --quiet HEAD || git commit -m "APIs from Azure APIM (auto-imported)"
        git push
